### ISSUE TITLE
Software Development Lifecycle Master Issue

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#972]
De-facto project manager @CodeSteele has suggested some important steps that will allow users who want to jump directly from tagged release to tagged release, without constantly being on the "rolling update" schedule of 

- [x] Add files that aren't relevant to traditional installs to be [excluded from release builds](https://maurobringolf.ch/2017/06/how-to-remove-files-from-github-releases-via-gitattributes/)

- [x] Provide a hard-coded version fallback to display on the site footer when an installation isn't associated with a Git repository

- [x] Add support in the `./install.sh` and `./update.sh` scripts for operating while not inside a Git repository

- [ ] Add support in `./update.sh` to update to the newest release build instead of the newest rolling release

- [ ] Update `./docker.sh` to allow updating through release versions instead of just rolling releases.

**Comment by CodeSteele** [comment]
This is based off the idea that we have ~10% of our traditional installs that we see right now are like this. I don't even know how they handle stuff like DB migrations...

**Comment by SlvrEagle23** [comment]
We've added release-build support to all installation types at this point. Marking this issue as complete.
